import { faker } from "@faker-js/faker";

export const companies = [
    {
        id: 0,
        name: faker.company.name(),
        address: {
            city: faker.location.city(),
            street: faker.location.street(),
            building: faker.location.buildingNumber(),
        },
        checked: true,
        employess: [
            {
                id: 115,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 215,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 315,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 488898,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 515,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 615,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 715,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 815,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 915,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 10,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 11,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 12,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
        ],
    },
    {
        id: 1,
        name: faker.company.name(),
        address: {
            city: faker.location.city(),
            street: faker.location.street(),
            building: faker.location.buildingNumber(),
        },
        employess: [
            {
                id: 13,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 14,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 15,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 16,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 17,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 18,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 19,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 20,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 21,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 22,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 23,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 24,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 25,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 26,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 27,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
        ],
        checked: false,
    },
    {
        id: 2,
        name: faker.company.name(),
        address: {
            city: faker.location.city(),
            street: faker.location.street(),
            building: faker.location.buildingNumber(),
        },
        employess: [
            {
                id: 28,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 29,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 30,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 31,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 32,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 33,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 34,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 35,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 36,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 37,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 38,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 39,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 40,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 41,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 42,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
        ],
        checked: false,
    },
    {
        id: 3,
        name: faker.company.name(),
        address: {
            city: faker.location.city(),
            street: faker.location.street(),
            building: faker.location.buildingNumber(),
        },
        employess: [
            {
                id: 43,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 44,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 45,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 46,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 47,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
        ],
        checked: false,
    },
    {
        id: 4,
        name: faker.company.name(),
        address: {
            city: faker.location.city(),
            street: faker.location.street(),
            building: faker.location.buildingNumber(),
        },
        employess: [
            {
                id: 48,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 49,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 50,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
        ],
        checked: false,
    },
    {
        id: 5,
        name: faker.company.name(),
        address: {
            city: faker.location.city(),
            street: faker.location.street(),
            building: faker.location.buildingNumber(),
        },
        employess: [
            {
                id: 51,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 52,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 53,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
            {
                id: 54,
                name: faker.person.fullName(),
                post: faker.person.jobType(),
                checked: false,
            },
        ],
        checked: false,
    },
];
